version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic:10:1, topic2:10:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  simple-producer:
    image: simple-producer:latest
    environment:
      KAFKA_HOST: "kafka"
      KAFKA_PORT: "9092"
      TOPIC: "test1"
  under-test:
    image: under-test
    environment:
      KAFKA_BROKER_HOST: "kafka:9092"
      KAFKA_TOPIC: "topic"
      DEFAULT_KAFKA_CONSUMER_GROUP: "localgroup"
      
      


   
